config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/shared/_comment_form.html.erb
<%= form_for(@comment, url: micropost_comments_url(@micropost_id),
    html: { id: "new-comment-mic-#{@micropost_id}" },
    remote: true) do |f| %>

  <div class="form-group field">
    <%= hidden_field_tag :micropost_id, @micropost_id %>
    <%= f.text_area :content, placeholder: "Leave a comment...",
            rows: 1, class: "form-control comment-textarea" %>
    <%= f.submit "Comment", class: "btn btn-success" %>
  </div>
  <div id="alert-mic-<%= @micropost_id %>">
    Cannot be blank or longer than 140 characters.
  </div>
<% end %>

app/views/shared/_error_message.html.erb
<% if object.errors.any? %>
  <div class="error_explanation">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<ol class="microposts" id="user-feed">
  <% if @feed_items.any? %>
    <%= render @feed_items %>
  <% end %>
</ol>
<%= will_paginate @feed_items %>

app/views/shared/_like_form.html.erb
<%= form_for(current_user.likes.build, html: { class: "like-forms" },
              remote: true) do |f| %>
  <%= hidden_field_tag :likeable_type, @likeable_type %>
  <%= hidden_field_tag :likeable_id, @likeable_id %>
  <button type="submit" class="btn-custom">
    <i class="far fa-thumbs-up"></i>
  </button>
<% end %>

app/views/shared/_message.html.erb
<% flash.each do |message_type, message| %>
  <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html: { id: 'micropost-form' },
              remote: true) do |f| %>
  <div class="form-group">
    <%= f.text_area :content, placeholder: "Compose new micropost...",
                    class: "form-control micropost-field", rows: 5 %>
  </div>
  <div class="form-group">
    <span class="picture text-muted">
      <%= f.file_field :picture, accept: 'image/jpeg, image/gif, image/png' %>
    </span>
  </div>
  <%= f.submit "Post", class: "btn btn-success" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_unlike_form.html.erb
<%= form_for(current_user.likes.find_by(likeable_type: @likeable_type,
        likeable_id: @likeable_id), html: { method: :delete,
        class: "like-forms" }, remote: true) do |f| %>
  <button type="submit" class="btn-custom">
    <i class="fas fa-thumbs-up unlike"></i>
  </button>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 70), current_user %>
<h1><%= current_user.name %></h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span id="user-microposts-count">
  <%= pluralize(current_user.microposts.count, "micropost") %>
</span>