config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small class="text-muted">
    This demo app is built by <a href="https://github.com/tianyuancuipan">Tianyuan Cui Pan</a>.
  </small>
</footer>

app/views/layouts/_footer_home.html.erb
<footer class="footer">
  <small class="text-muted">
    This demo app is built by <a href="https://github.com/tianyuancuipan" target="_blank">Tianyuan Cui Pan</a>.
    <a href="https://www.freepik.com/free-photos-vectors/background">Background vector created by rawpixel.com - www.freepik.com</a>.
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-expand-lg fixed-top">
  <%= link_to "Twitter Clone 2.0", root_path, class: "navbar-brand", id: "logo" %>

  <div class="collapse navbar-collapse">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
      <% if logged_in? %>
        <li class="nav-item"><%= link_to "Discover", users_path, class: "nav-link" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", current_user, class: "dropdown-item" %>
            <%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item"><%= link_to "Log in", login_path, class: "nav-link" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add font-awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossorigin="anonymous">
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/message' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Add font-awesome CDN -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"
          integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr"
          crossorigin="anonymous">
    <%= render 'layouts/shim' %>
  </head>

  <body class="home">
    <%= render 'layouts/header' %>
    <div class="container">
      <%= render 'shared/message' %>
      <%= yield %>
      <%= render 'layouts/footer_home' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>